# Generated by Django 5.2.8 on 2025-11-20 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('template_id', models.CharField(max_length=128)),
                ('payload_json', models.JSONField(default=dict)),
                ('channels_order', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('sent', 'sent'), ('delivered', 'delivered'), ('failed', 'failed'), ('partially_failed', 'partially_failed')], default='queued', max_length=32)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=32)),
                ('provider', models.CharField(max_length=64)),
                ('attempt_no', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('retry_scheduled', 'retry_scheduled')], max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=128, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='notifications.notification')),
            ],
        ),
    ]
